op n adj x =
	(n == 1) : x
	x + (n - 1) adj 1 rot x

op n stripe x = x * n adj (iota (rho x)[2]) o.== iota (rho x)[2]

op n mark x =
	starts = n == +/ transp n stripe n adj x o.== x
	(n - 1) + 1 take starts sel iota rho x

x = 'mjqjpqmgbljsphdztnvjfqwrcgsmlb'

'sample start packet is'

4 mark x

'sample message marker is'

14 mark x

) get "input.ivy"

'input start packet is'

4 mark input

'input message marker is'

14 mark input
